const actionTypes = {
    GET_HOME: 'GET_HOME',
    // GET_BANNERS: 'GET_BANNERS',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',

    //user
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT'
}

export default actionTypes;